/** 50 известных актёров (Голливуд + РФ) для автоподписи рейтинга. */
export const GAME_ACTOR_NAMES = [
	"Tom Hanks",
	"Meryl Streep",
	"Leonardo DiCaprio",
	"Denzel Washington",
	"Julia Roberts",
	"Brad Pitt",
	"Angelina Jolie",
	"Robert De Niro",
	"Al Pacino",
	"Morgan Freeman",
	"Scarlett Johansson",
	"Johnny Depp",
	"Natalie Portman",
	"Will Smith",
	"Sandra Bullock",
	"Keanu Reeves",
	"Jennifer Lawrence",
	"Christian Bale",
	"Cate Blanchett",
	"Samuel L. Jackson",
	"Harrison Ford",
	"Nicole Kidman",
	"Matt Damon",
	"Anne Hathaway",
	"Joaquin Phoenix",
	"Константин Хабенский",
	"Данила Козловский",
	"Елизавета Боярская",
	"Сергей Безруков",
	"Иван Охлобыстин",
	"Чулпан Хаматова",
	"Александр Петров",
	"Никита Ефремов",
	"Евгений Миронов",
	"Ингеборга Дапкунайте",
	"Сергей Гармаш",
	"Леонид Ярмольник",
	"Олег Табаков",
	"Владимир Машков",
	"Юлия Пересильд",
	"Виктор Сухоруков",
	"Фёдор Бондарчук",
	"Мария Аронова",
	"Юрий Быков",
	"Виктория Толстоганова",
	"Кирилл Пирогов",
	"Нонна Гришеева",
	"Янина Студилина",
	"Максим Матвеев",
	"Полина Агуреева"
] as const;
export const GAME_ACTOR_NAME_COUNT = GAME_ACTOR_NAMES.length;
